### ISSUE TITLE
Set logging fn example

### ISSUE THREAD

**Issue by bahulneel** [grammarly/omniconf#2]
Hi,

The example in the README for set-logging-fn doesn't seem to work with the current version of timbre. As best as I can tell the closest match in the timbre README is https://github.com/ptaoussanis/timbre#log-levels-and-ns-filters

**Comment by alexander-yakushev** [comment]
Hello @bahulneel,

I have to admit the example of using Timbre as logging functions is very contrived. This is because Timbre's public-facing API consists of macros exclusively, so I had to dig into implementation details to get something that is a function. It is no surprise that my example broke in the newer version. I personally use that code with `com.taoensso/timbre "4.1.4"`, and it works for me. 

Could you please try that version of timbre and see if the code from README works with it? If that is the case, I will look into what has to be changed in it to be compatible with the newest timbre.

**Comment by bahulneel** [comment]
That works but I do have to do `(vec args)` in the delay otherwise I get an exception.

**Comment by alexander-yakushev** [comment]
Alright, I will try to take a closer look at this soon and get back to you with the results. Thanks for reporting!

**Comment by alexander-yakushev** [comment]
Indeed, latest Timbre changed API a bit. I've updated the README to reflect the changes. You were right about `vec`. Thank you again!

**Comment by bahulneel** [comment]
Thanks for a great library.
